package inventory

// ObservedAudio is one observed audio file as the inventory stores it, with the
// generation credential recorded beside it when a generation wrote that path.
// It is deliberately the storage shape: the SQL, its null handling and its
// column mapping stay with the adapter, while the mapping onto a planning fact
// belongs to the task that plans with it.
type ObservedAudio struct {
	Path    string
	Size    int64
	Mtime   int64
	Bitrate int64
	Format  string
	// Generated is the credential of the generation that last wrote this path,
	// nil when the path was never generated by this app.
	Generated *GeneratedCredential
}

// GeneratedCredential is the recorded fact of one generation: which encoder
// wrote the file and the content proxy a later plan compares against.
type GeneratedCredential struct {
	Codec       string
	BitrateKbps int
	Mode        string
	Size        int64
	Mtime       int64
}

// BitrateUpdate is one observed bitrate to write back onto an entry. The probed
// rate is an inventory fact, so it crosses to the adapter as this type.
type BitrateUpdate struct {
	Path        string
	BitrateKbps int64
}
